config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  get '/', to: 'home#index', as: 'home'
  root "groups#index"
  resources :groups do
    resources :entities
  end
end

app/models/entity.rb
class Entity < ApplicationRecord
  belongs_to :user, foreign_key: :user_id
  belongs_to :group, foreign_key: :group_id

  validates :name, length: { maximum: 80 }, presence: true
  validates :amount, presence: true, numericality: { greater_than_or_equal_to: 0 }
  validates :user_id, presence: true
end

app/controllers/entities_controller.rb
class EntitiesController < ApplicationController
  load_and_authorize_resource
  before_action :set_entity, only: %i[show edit update destroy]

  # GET /entities or /entities.json
  def index
    @group = Group.find(params[:group_id])
    @entities = Entity.where(group_id: params[:group_id])
  end

  # GET /entities/1 or /entities/1.json
  def show; end

  # GET /entities/new
  def new
    @entity = Entity.new
    @group = Group.find(params[:group_id])
    @entity = @group.entities.build
  end

  # GET /entities/1/edit
  def edit; end

  # POST /entities or /entities.json
  def create
    @entity = Entity.new(entity_params)
    @entity.user_id = current_user.id

    respond_to do |format|
      if @entity.save
        format.html { redirect_to group_entities_path, notice: 'Entity was successfully created.' }
        format.json { render :show, status: :created, location: @entity }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @entity.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /entities/1 or /entities/1.json
  def update
    respond_to do |format|
      if @entity.update(entity_params)
        format.html { redirect_to entity_url(@entity), notice: 'Entity was successfully updated.' }
        format.json { render :show, status: :ok, location: @entity }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @entity.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /entities/1 or /entities/1.json
  def destroy
    @entity.destroy

    respond_to do |format|
      format.html { redirect_to entities_url, notice: 'Entity was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_entity
    @entity = Entity.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def entity_params
    params.require(:entity).permit(:user_id, :group_id, :name, :amount)
  end
end

app/helpers/entities_helper.rb
module EntitiesHelper
end

app/views/entities/_entity.html.erb
<div id="<%= dom_id entity %>">
  


  
      <div class='store-cont name-amount'>
        <p>
          <%= entity.name %>:
        </p>   
           
        <p>$<%= entity.amount %></p>   
      </div>     
  

  

  

</div>

app/views/entities/_form.html.erb
<%= form_with(model: [@group, @entity], url: group_entities_path(@group)) do |form| %>
  <% if entity.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(entity.errors.count, "error") %> prohibited this item from being saved:</h2>

      <ul>
        <% entity.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

    <div>    
      <%= form.select :group_id, Group.all.collect {|group| [group. name, group.id]},{
      include_blank: true} , :required => 'required',   class:"form-select", hidden: true %>
    </div>

    <div class='add-store1'>
      <%= form.text_field :name, placeholder: "Name" %>
   

  
      <%= form.number_field :amount, placeholder: "Amount" %>

    
<div class='add-store-btn'>
    <div class='add-cart'>
      <%= form.submit "Add purchase", class:' log-out-button1' %>
    </div>

    <div class='add-cart'>
    <%= link_to "Back to purchases", group_entities_path, class:' log-out-button1' %>
  </div>
</div>

<% end %>

app/views/entities/edit.html.erb
<h1>Editing cart</h1>

<%= render "form", entity: @entity %>

<br>

<div>
  <%= link_to "Show this entity", @entity %> |
  <%= link_to "Back to entities", entities_path %>
</div>

app/views/entities/index.html.erb
<div class='nav-section'>
  <nav class='nav-container'>
    <a class='logo' href="#">World carts</a>    
    <h2 class='title'>Purchases</a>
    <h2><%= button_to 'Log out', destroy_user_session_path, method: :delete, class: 'log-out-xd' %></h2>      
  </nav>
</div>

<div class='page-cont'>
  
  <div class='total-cont'>
    <div class='total-cont1'>
    <h2>Total amount:</h2>
    <h2>$<%= Group.total_amount(@group) %></h2>
  </div>
  </div>
  
  <br>
  
    <div id="entities">
      <% @entities.each do |entity| %>
        <%= render entity %>
        <br>
      <% end %>
    </div>

    <div class='add-store-btn'>
      <div class='add-cart'>
       <%= link_to "New purchase", new_group_entity_path, class: "log-out-button1" %>
      </div>
        
      <div class='add-cart'>
        <%= link_to "Back to carts", groups_path, class: "log-out-button1" %>
    </div>
    </div>
</div>

app/views/entities/new.html.erb
<div class='nav-section'>
  <nav class='nav-container'>
    <a class='logo' href="#">World carts</a>    
    <h2 class='title'>Purchases</a>
    <h2><%= button_to 'Log out', destroy_user_session_path, method: :delete, class: 'log-out-xd' %></h2>      
  </nav>
</div>

<div class='add-store'>
  <div class='total-cont'>
  <h1>New purchase</h1>
  </div>

  <%= render "form", entity: @entity %>

  <br>

  
</div>

app/views/entities/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @entity %>

<div>
  <% if can? :update, @group %>
    <%= link_to "Edit this entity", edit_entity_path(@entity) %> |
  <%end%>
  <%= link_to "Back to entities", entities_path %>
  <% if can? :update, @group %>
    <%= button_to "Destroy this entity", @entity, method: :delete %>
  <%end%>
</div>