config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  get '/', to: 'home#index', as: 'home'
  root "groups#index"
  resources :groups do
    resources :entities
  end
end

app/models/group.rb
class Group < ApplicationRecord
  belongs_to :user, foreign_key: :user_id
  has_many :entities

  validates :name, length: { maximum: 80 }, presence: true

  def self.total_amount(group)
    total_amount = 0
    group.entities.each do |entity|
      total_amount += entity.amount
    end
    total_amount
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  load_and_authorize_resource
  before_action :set_group, only: %i[show edit update destroy]

  # GET /groups or /groups.json
  def index
    @groups = Group.where(user_id: current_user.id)
  end

  # GET /groups/1 or /groups/1.json
  def show; end

  # GET /groups/new
  def new
    @group = Group.new
  end

  # GET /groups/1/edit
  def edit; end

  # POST /groups or /groups.json
  def create
    @group = Group.new(group_params)
    @group.user_id = current_user.id
    respond_to do |format|
      if @group.save
        format.html { redirect_to groups_path, notice: 'Group was successfully created.' }
        format.json { render :show, status: :created, location: @group }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /groups/1 or /groups/1.json
  def update
    respond_to do |format|
      if @group.update(group_params)
        format.html { redirect_to group_url(@group), notice: 'Group was successfully updated.' }
        format.json { render :show, status: :ok, location: @group }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /groups/1 or /groups/1.json
  def destroy
    @group.destroy

    respond_to do |format|
      format.html { redirect_to groups_url, notice: 'Group was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_group
    @group = Group.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def group_params
    params.require(:group).permit(:name, :icon)
  end
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/views/groups/_form.html.erb
<%= form_with(model: group, url: groups_path(@group)) do |form| %>
  <% if group.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(group.errors.count, "error") %> prohibited this group from being saved:</h2>

      <ul>
        <% group.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

<div class='add-store1'>
  
    <%= form.text_field :name, placeholder: "Store" %> 
    
    <%= form.text_field :icon, placeholder: "Icon" %> 
 
<div class='add-store-btn'>
  <div class='add-cart'>
    <%= form.submit "Add cart", class: "submit-btn log-out-button1" %>
  </div>

    <div class='add-cart'>
      <%= link_to "Back to carts", groups_path, class:' log-out-button1' %>
    </div>
</div>
    
<div>
<% end %>

app/views/groups/_group.html.erb
<div class='group-cont' id="<%= dom_id group %>">  
  <%= link_to group_entities_path(:group_id => group.id), style: "text-decoration: none; color: black;" do %>
  
  <div class='store-cont'>
    <p class='data-align'>
      <img class='icon' src='<%= group.icon %>'>
      <%= group.name %>
    </p>
                 
        <p>$<%= Group.total_amount(group) %></p>            
  </div>
  <br>
    <% end %>
</div>

app/views/groups/edit.html.erb
<h1>Editing store</h1>

<%= render "form", group: @group %>

<br>

<div>
  <%= link_to "Show this group", @group %> |
  <%= link_to "Back to groups", groups_path %>
</div>

app/views/groups/index.html.erb
<div class='nav-section'>
  <nav class='nav-container'>
    <a class='logo' href="#">World carts</a>    
    <h2 class='title'>Carts</a>
    <h2><%= button_to 'Log out', destroy_user_session_path, method: :delete, class: 'log-out-xd' %></h2>      
  </nav>
</div>

<div class='page-cont'>
  <br>
  <div id="groups">
    <% @groups.each do |group| %>
    <%= render group %>   
    <% end %> 
    <br>
  </div>
  <%= link_to "New cart", new_group_path, class: "new-group" %>
</div>

app/views/groups/new.html.erb
<div class='nav-section'>
  <nav class='nav-container'>
    <a class='logo' href="#">World carts</a>    
    <h2 class='title'>Carts</a>
    <h2><%= button_to 'Log out', destroy_user_session_path, method: :delete, class: 'log-out-xd' %></h2>      
  </nav>
</div>


    <div class='total-cont'>
    <h1>Add a store and it icon</h1>
    </div>
    
    
      <%= render "form", group: @group %>

      
    
  

app/views/groups/show.html.erb
<p style="color: green"><%= notice %></p>

<% if can? :manage, @group %>
<%= render @group %>
<%end%>

<div>
  <% if can? :update, @group %>
    <%= link_to "Edit this group", edit_group_path(@group) %> |
  <%end%>
  <%= link_to "Back to groups", groups_path %>
  <% if can? :update, @group %>
    <%= button_to "Destroy this group", @group, method: :delete %>
  <%end%>
</div>